Feature/#85
BraintagsGmbH/vertx-pojo-mapper pull request #100
Opened 2017-04-26 08:41 UTC by remi128

implementation of issue #85 data versioning and conversion

2017-04-28 09:02 UTC, sschmittBt requested changes
Instead of the IMapperVersion interface, that every class has to implement if it wants versioning, wouldn't it be nicer if the version info would be added dynamically to saved entities? Similar to how Jackson handles the @class values for polymorphism. This way, the user doesn't need to care for anything, can not manipulate the version and produce unexpected behaviour, and can simply control everything via the annotation.

2017-04-28 09:02 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/write/impl/AfterUpdateHandler.java
> + *
Missing comment

2017-04-28 09:02 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/write/impl/BeforeInsertHandler.java
> +          writeObject.getDataStore());
Does every observer need its own event, or can you move the event creation outside of the loop?

2017-04-28 09:02 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/write/impl/BeforeUpdateHandler.java
> + *
Missing comment

2017-04-28 09:02 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/annotation/VersionInfo.java
> +  ObserverEventType eventType() default ObserverEventType.BEFORE_UPDATE;
Could you add the allowed event types to the comment?

2017-04-28 09:02 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/mapping/impl/AbstractMapper.java
> +  private void computeIndize(Map<String, IIndexDefinition> definitions) {
Either indexes or indices, but not indize

2017-05-02 14:56 UTC, remi128 commented
yes, would be nice, especially cause user would not be able to manipulate the version number. Unfortunately i need the version number in access from an entity, when the versioning is running in phase BEFORE_UPDATE for instance.

2017-05-02 15:01 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/write/impl/AfterUpdateHandler.java
> + *
done

2017-05-02 15:04 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/write/impl/BeforeInsertHandler.java
> +          writeObject.getDataStore());
good - done

2017-05-02 15:04 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/write/impl/BeforeUpdateHandler.java
> + *
done

2017-05-02 15:07 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/annotation/VersionInfo.java
> +  ObserverEventType eventType() default ObserverEventType.BEFORE_UPDATE;
done

2017-05-02 15:08 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/mapping/impl/AbstractMapper.java
> +  private void computeIndize(Map<String, IIndexDefinition> definitions) {
done

2017-05-02 15:14 UTC, sschmittBt requested changes

2017-05-02 15:14 UTC, sschmittBt commented on vertx-pojo-mapper-common-test/src/main/java/de/braintags/vertx/jomnigate/testdatastore/TestDataVersioning.java
> +    context.assertEquals(88l, vi2.getMapperVersion(), "for an update the version should NOT be set");
Why should the new version be "881" if it was "51" before and you set it to "88"?

2017-05-02 15:16 UTC, remi128 commented on vertx-pojo-mapper-common-test/src/main/java/de/braintags/vertx/jomnigate/testdatastore/TestDataVersioning.java
> +    context.assertEquals(88l, vi2.getMapperVersion(), "for an update the version should NOT be set");
88l -> 88 Long

2017-05-02 15:20 UTC, sschmittBt commented on vertx-pojo-mapper-common-test/src/main/java/de/braintags/vertx/jomnigate/testdatastore/TestDataVersioning.java
> +    context.assertEquals(88l, vi2.getMapperVersion(), "for an update the version should NOT be set");
Wow... that "l" looks seriously like a 1 in the comparison... my bad.

2017-05-03 07:21 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/mapping/impl/AbstractMapper.java
> +  private void computeIndize(Map<String, IIndexDefinition> definitions) {
Did you commit it? For me it still says "indize"

2017-05-03 08:53 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/mapping/impl/AbstractMapper.java
> +  private void computeIndize(Map<String, IIndexDefinition> definitions) {
ups - second method, pushed now

2017-05-03 09:10 UTC, sschmittBt approved these changes

2017-05-03 09:10 UTC, merged