Feature/expertfb5 bulk operations
BraintagsGmbH/vertx-pojo-mapper pull request #138
Opened 2017-09-02 11:19 UTC by sschmittBt

Changed mongo write to use bulk write

2017-09-04 08:50 UTC, mpluecker requested changes

2017-09-04 08:50 UTC, mpluecker commented on vertx-pojo-mapper-common-test/src/main/java/de/braintags/vertx/jomnigate/testdatastore/TestUpdate.java
> +    checkUpdateWithQuery(updatedTest3, tester3, WriteAction.NOT_MATCHED, query, context);
Macht das nicht den testUpdateWithNoneMatchingQuery obsolet?

2017-09-04 08:50 UTC, mpluecker commented on vertx-pojongo/src/main/java/de/braintags/vertx/jomnigate/mongo/dataaccess/MongoWrite.java
> +    if (updateResult.getMatchedCount() != 0 && updateResult.getMatchedCount() == updateResult.getModifiedCount()) {
Hier muss geprüft werden, ob getMatchedCount() == Anzahl der entities im BulkWrite.

2017-09-04 08:50 UTC, mpluecker commented on vertx-pojongo/src/main/java/de/braintags/vertx/jomnigate/mongo/dataaccess/MongoWrite.java
> +      resultHandler.handle(Future.failedFuture(new WriteException("Matched " + updateResult.getMatchedCount()
Hier nicht failen sondern succeed mit WriteAction.UNKNOWN

2017-09-05 10:24 UTC, sschmittBt commented on vertx-pojongo/src/main/java/de/braintags/vertx/jomnigate/mongo/dataaccess/MongoWrite.java
> +    if (updateResult.getMatchedCount() != 0 && updateResult.getMatchedCount() == updateResult.getModifiedCount()) {
Momentan stimmt es so, weil Update mit Query sowieso nur 1 Entity zulässt, und auf 0 geprüft wird.

Wenn mal mehr als einer erlaubt wird, wäre das hier auch nicht die richtige Stelle für die Prüfung, weil die Methode für jede Entity einzeln aufgerufen wird.

2017-09-05 10:24 UTC, sschmittBt commented on vertx-pojongo/src/main/java/de/braintags/vertx/jomnigate/mongo/dataaccess/MongoWrite.java
> +      resultHandler.handle(Future.failedFuture(new WriteException("Matched " + updateResult.getMatchedCount()
Wie eben geklärt, UNKNOWN bringt dem User nicht viel, stört bei der Save Action, und kann bei Begrenzung von Update mit Query auf 1 Datensatz eh nicht wirklich vorkommen.

Man könnte den else Teil wahrscheinlich auch weg lassen, da er jetzt nur auftreten könnte wenn Mongo was seltsames macht (1 matchen aber nicht updaten?)

2017-09-05 10:31 UTC, mpluecker approved these changes

2017-09-05 10:32 UTC, merged