IndexedField column name removal
BraintagsGmbH/vertx-pojo-mapper pull request #92
Opened 2017-04-11 14:46 UTC by sschmittBt

Reworked IndexedField to remove the fixed column name and instead fetch the column name on query execution from the mapper

2017-04-12 13:13 UTC, remi128 requested changes
FieldContition line 135 has compiler error

2017-04-12 14:14 UTC, remi128 requested changes

2017-04-12 14:14 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/IIndexedField.java
>    static IIndexedField getIndexedField(String name, Class<?> pojoClass)
documentation a bit please

2017-04-12 14:14 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/IIndexedField.java
> +  default String getColumnName(IDataStore<?, ?> datastore) {
documentation a bit please

2017-04-12 14:14 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/IIndexedField.java
> +  default String getColumnName(IMapper<?> mapper) {
documentation a bit please

2017-04-12 14:14 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/IIndexedField.java
> +      throw new de.braintags.vertx.jomnigate.exception.NoSuchFieldException(getFieldName());
We have both exception types in the class: java.land.NoSuchFieldException and de.braintags.vertx.jomnigate.exception.NoSuchFieldException. Is that wished?

2017-04-12 14:14 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/impl/AbstractQueryExpression.java
>          // can not use datastore object mapper here because only the JSON datastore has the object mapper
isn't it useful to overwrite this method in MongoQueryExpression where you have access to the object mapper?

2017-04-12 14:14 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/impl/IndexedField.java
> +    if (obj == null)
could it make sense to get one line like obj == null ||getClass() != obj.getClass ?

2017-04-12 14:14 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/mapping/impl/MappedIdFieldImpl.java
> +    if (this == obj)
duplicate, cause following super call does the same

2017-04-13 08:14 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/IIndexedField.java
> +      throw new de.braintags.vertx.jomnigate.exception.NoSuchFieldException(getFieldName());
I think it makes sense, the java one is thrown if the IndexedField is missing in the java class, and the jomnigate one is thrown when a field could not be found inside the mapper.

2017-04-13 08:22 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/impl/AbstractQueryExpression.java
>          // can not use datastore object mapper here because only the JSON datastore has the object mapper
MySql could also have a GeoSearchArgument, so we have to have a solution for both cases.
But nevertheless, this whole block will be removed in an upcoming change.

2017-04-13 08:23 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/impl/IndexedField.java
> +    if (obj == null)
I just use the auto generated equals method from Eclipse, but I don't think the compiler really cares in what way this expression is written.

2017-04-13 08:26 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/mapping/impl/MappedIdFieldImpl.java
> +    if (this == obj)
Fixed

2017-04-13 08:27 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/IIndexedField.java
>    static IIndexedField getIndexedField(String name, Class<?> pojoClass)
Added

2017-04-13 08:27 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/IIndexedField.java
> +  default String getColumnName(IDataStore<?, ?> datastore) {
Added

2017-04-13 08:27 UTC, sschmittBt commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/IIndexedField.java
> +  default String getColumnName(IMapper<?> mapper) {
Added

2017-04-13 08:47 UTC, remi128 commented on vertx-pojo-mapper-common/src/main/java/de/braintags/vertx/jomnigate/dataaccess/query/impl/AbstractQueryExpression.java
>          // can not use datastore object mapper here because only the JSON datastore has the object mapper
the mysql search expression for Geo differs a lot from the one of mongo, but ok, we will change that later together with the refactoring of mysql

2017-04-13 08:50 UTC, remi128 approved these changes

2017-04-13 08:50 UTC, remi128 commented
after resolviong conflicts merging ok

2017-04-13 13:04 UTC, mpluecker submitted a review, later dismissed
Code look ok for me.

2017-04-13 13:09 UTC, mpluecker commented
By the way, do we still need the IdField and IMappedIdField and their implementations? For example an IndexedField is not equals to a MappedIdFieldImpl even if they reporesent the same field of a mapped class.

2017-04-13 13:16 UTC, sschmittBt commented
@mpluecker:
We have two use cases: 
Make a query to an ID field of a mapper:
`ISearchCondition.isEqual(mapper.getIdField(),"1234")`
Get some field properties of the ID field of a mapper, e.g. the property accessor:
mapper.getIdField().getPropertyAccessor().writeData(...)

We could make to seperate properties, getQueryIdField and getMappedIdField for example, but with this we can simply use getIdField().getField() to get to the mapped field.

2017-04-13 13:22 UTC, merged

2017-04-13 13:32 UTC, remi128 commented
ok, i did not really recognize intensively, that the api of IMapper was changed that way.

The api previously returned an IProperty for getIdField.
IProperty contains all information like fieldName, columnName etc. and has the information isIdField.
That way it contains all information already, which are now redundant inside the IMappedField and IIndexed field. Additionally the IMappedIdField contains the IProperty. 
Additionally the IMapper returns an IProperty for getField(), but an IMappedIdField - which is not an instance of IProperty - for getIdField(), so that we are mixing responsibilites of IMapper now, which are IMO not very logic.
Please find another solution here

2017-04-13 14:17 UTC, sschmittBt commented
Continued in #95